"use client"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SnackbarProvider } from 'notistack';
import Header from "@/components/header/header";
import { Provider } from 'react-redux';
import { PersistGate } from "redux-persist/integration/react";
import { persister, store } from '@/redux/store';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SnackbarProvider maxSnack={3} autoHideDuration={1500}>
          <Provider store={store}>
            <PersistGate loading={null} persistor={persister}>
              <Header />
              {children}
            </PersistGate>
          </Provider>
        </SnackbarProvider>
      </body>
    </html>
  );
}
